-- SQL schema for Indah Cell Stock Counter

-- Create the main table for tracking stock
CREATE TABLE public.stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_cabang TEXT NOT NULL CHECK (nama_cabang IN ('Soko', 'Mbutoh')),
  produk TEXT NOT NULL DEFAULT 'HP',
  stok_pagi INT NOT NULL,
  stok_sekarang INT NOT NULL,
  tanggal DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add a unique constraint to prevent duplicate entries for the same branch and date
ALTER TABLE public.stock
ADD CONSTRAINT unique_stock_entry UNIQUE (nama_cabang, tanggal);

-- Create the table for logging stock history
CREATE TABLE public.stock_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stock_id BIGINT NOT NULL REFERENCES public.stock(id) ON DELETE CASCADE,
  perubahan INT NOT NULL,
  stok_sebelum INT NOT NULL,
  stok_sesudah INT NOT NULL,
  -- user_id UUID REFERENCES auth.users(id), -- Optional: uncomment to track which user made the change
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security (RLS) for both tables
ALTER TABLE public.stock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_history ENABLE ROW LEVEL SECURITY;

-- Create policies for the 'stock' table
CREATE POLICY "Allow public read access for stock"
ON public.stock FOR SELECT USING (true);

CREATE POLICY "Allow insert for authenticated users on stock"
ON public.stock FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Allow update for authenticated users on stock"
ON public.stock FOR UPDATE USING (auth.role() = 'authenticated');

-- Create policies for the 'stock_history' table
CREATE POLICY "Allow read access for authenticated users on stock_history"
ON public.stock_history FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow insert for authenticated users on stock_history"
ON public.stock_history FOR INSERT WITH CHECK (auth.role() = 'authenticated');


-- IMPORTANT: Enable real-time updates on tables.
-- You must do this in your Supabase dashboard under Database > Replication.
-- Or you can run these commands in the SQL editor:
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock;
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock_history;

-- Create a function to update stock and log history atomically
CREATE OR REPLACE FUNCTION public.update_stock_and_log_history(
  p_stock_id BIGINT,
  p_perubahan INT
)
RETURNS VOID AS $$
DECLARE
  v_stok_sebelum INT;
  v_stok_sesudah INT;
BEGIN
  -- Get the current stock amount and lock the row
  SELECT stok_sekarang INTO v_stok_sebelum
  FROM public.stock
  WHERE id = p_stock_id
  FOR UPDATE;

  -- Calculate the new stock amount
  v_stok_sesudah := v_stok_sebelum + p_perubahan;

  -- Update the stock amount
  UPDATE public.stock
  SET stok_sekarang = v_stok_sesudah
  WHERE id = p_stock_id;

  -- Insert a record into the history table
  INSERT INTO public.stock_history (stock_id, perubahan, stok_sebelum, stok_sesudah)
  VALUES (p_stock_id, p_perubahan, v_stok_sebelum, v_stok_sesudah);
END;
$$ LANGUAGE plpgsql;

-- Create a function to create new daily stock entries based on the last available data
CREATE OR REPLACE FUNCTION public.create_daily_stock_entries()
RETURNS TEXT AS $$
DECLARE
  v_cabang TEXT;
  v_last_stock RECORD;
  v_today DATE := CURRENT_DATE;
  v_entries_created INT := 0;
  v_cabang_list TEXT[] := ARRAY['Mbutoh', 'Soko'];
BEGIN
  -- Loop through each branch
  FOREACH v_cabang IN ARRAY v_cabang_list
  LOOP
    -- Check if an entry for today already exists for the branch
    IF NOT EXISTS (SELECT 1 FROM public.stock WHERE nama_cabang = v_cabang AND tanggal = v_today) THEN
      -- Find the most recent stock record for the branch
      SELECT * INTO v_last_stock
      FROM public.stock
      WHERE nama_cabang = v_cabang
      ORDER BY tanggal DESC
      LIMIT 1;

      -- If a previous record exists, create a new one for today
      IF FOUND THEN
        INSERT INTO public.stock (nama_cabang, produk, stok_pagi, stok_sekarang, tanggal)
        VALUES (v_cabang, v_last_stock.produk, v_last_stock.stok_sekarang, v_last_stock.stok_sekarang, v_today);
        v_entries_created := v_entries_created + 1;
      END IF;
    END IF;
  END LOOP;

  RETURN 'Created ' || v_entries_created || ' new daily stock entries.';
END;
$$ LANGUAGE plpgsql;
