-- SQL schema for Indah Cell Stock Counter

-- Create the main table for tracking stock
CREATE TABLE public.stock (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nama_cabang TEXT NOT NULL CHECK (nama_cabang IN ('Soko', 'Mbutoh')),
  produk TEXT NOT NULL DEFAULT 'HP',
  stok_pagi INT NOT NULL,
  stok_sekarang INT NOT NULL,
  tanggal DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add a unique constraint to prevent duplicate entries for the same branch and date
ALTER TABLE public.stock
ADD CONSTRAINT unique_stock_entry UNIQUE (nama_cabang, tanggal);

-- Enable Row Level Security (RLS) for the table
ALTER TABLE public.stock ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows public read access to all stock data
CREATE POLICY "Allow public read access"
ON public.stock
FOR SELECT
USING (true);

-- Create a policy that allows authenticated users to insert new stock data
-- This is a basic policy; for production, you might want more specific roles.
CREATE POLICY "Allow insert for authenticated users"
ON public.stock
FOR INSERT
WITH CHECK (auth.role() = 'authenticated');

-- Create a policy that allows authenticated users to update stock data
CREATE POLICY "Allow update for authenticated users"
ON public.stock
FOR UPDATE
USING (auth.role() = 'authenticated');

-- IMPORTANT: Enable real-time updates on the 'stock' table.
-- You must do this in your Supabase dashboard under Database > Replication.
-- Supabase will then automatically publish changes to subscribed clients.
-- Or you can run this command in the SQL editor:
ALTER PUBLICATION supabase_realtime ADD TABLE public.stock;
